- title: "Deploying Rails on a single server with Kamal"
  description: "Here’s one way of a cloud-independent deployment of Rails, Sidekiq, PostgreSQL, and Redis on single virtual server with Kamal."  
  url: "https://nts.strzibny.name/deploying-rails-single-server-kamal/"
- title: "How to deploy Rails with Kamal and SSL certificate on any VPS"
  description: "Deploy Rails with Kamal and SSL certificate on any VPS"
  url: "https://guillaumebriday.fr/how-to-deploy-rails-with-kamal-and-ssl-certificate-on-vps"
- title: "Using Kamal to host multiple Apps on a single server"
  description: "Use the Kamal deployment tool to host multiple Applications on a single server instance"
  url: "https://www.erikminkel.com/2023/09/29/using-kamal-to-host-multiple-apps-on-a-single-server/"
- title: "Deploy your Rails 7 app with Kamal and CI/CD"
  description: "We'll run through an example utilizing the Kamal gem to deploy our Ruby on Rails application to a server with BitBucket Pipelines."
  url: "https://www.erikminkel.com/2023/10/18/deploy-your-rails-7-app-with-kamal-and-ci-cd/"
