service: kamal-directory
image: ashwinmk2016/kamal-directory

servers:
  web:
    hosts:
      - 5.161.126.59

proxy:
  ssl: true
  host: kamal.directory
  app_port: 3000

registry:
  username: ashwinmk2016
  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  clear:
    RUBY_YJIT_ENABLE: 1
  secret:
    - RAILS_MASTER_KEY
    - GITHUB_CLIENT_ID
    - GITHUB_SECRET
    - GOOGLE_ANALYTICS_ID
volumes:
  - "storage:/rails/storage"
  
aliases:
  shell: app exec --interactive --reuse "bash"
  console: app exec -r -i "bin/rails console"
  about: app exec -r -i "bin/rails about"
  
builder:
  arch:
    - amd64